# Generated by Django 5.2.8 on 2025-11-12 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.IntegerField(help_text='В процентах', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Размер скидки'),
        ),
    ]
