# Generated by Django 5.2.8 on 2025-12-17 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_discount_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_order'], 'permissions': (('can_set_status', 'Возможность настройки статуса'),), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.discount', verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(max_length=70, verbose_name='Страна'),
        ),
    ]
