# Generated by Django 5.2.8 on 2025-11-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todod',
            new_name='Todos',
        ),
    ]
