# Generated by Django 5.2.8 on 2025-11-12 14:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Имя')),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('date', models.TimeField(auto_now_add=True)),
                ('status_feed_back', models.CharField(choices=[('NEW', 'Новая обартная связь'), ('PCD', 'Обработано')], max_length=3, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название статьи', max_length=70, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='Подзаголовок')),
                ('preview', models.CharField(help_text='Отображается в списке статей', max_length=300, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Превью')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('photo', models.ImageField(upload_to='images', verbose_name='Изображения')),
                ('date', models.TimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Имя')),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('date', models.TimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-date'],
            },
        ),
    ]
