# Generated by Django 5.2.8 on 2025-11-12 14:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Введите описание', max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Описание')),
                ('date', models.TimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to='images', verbose_name='Изображения')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.image', verbose_name='Заглавная картинка'),
        ),
    ]
