# Generated by Django 5.2.8 on 2025-11-12 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_image_remove_article_photo_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.TextField(blank=True, default='', verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Введите описание', max_length=150, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Описание'),
        ),
    ]
