# Generated by Django 5.2.8 on 2025-11-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_subtitle_alter_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='preview',
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подзаголовок'),
        ),
    ]
