# Generated by Django 5.2.8 on 2025-12-14 04:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(help_text='Тема', max_length=70, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2025, 12, 14)),
            preserve_default=False,
        ),
    ]
