# Generated by Django 5.2.8 on 2025-12-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_feedback_title_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status_feed_back',
            field=models.CharField(choices=[('NEW', 'Новая обартная связь'), ('PCD', 'Обработано')], default='NEW', max_length=3, verbose_name='Статус'),
        ),
    ]
